services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ehs_user
      POSTGRES_PASSWORD: ehs_pass
      POSTGRES_DB: ehs
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data:/data

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

  api:
    build: .
    environment:
      DATABASE_DSN: postgresql://ehs_user:ehs_pass@db:5432/ehs
      AWS_REGION: ${AWS_REGION}
      BEDROCK_MODEL_ID: ${BEDROCK_MODEL_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}   
    depends_on:
      - db
    ports:
      - "8001:8000"
    volumes:
      - ./data:/data 
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]

volumes:
  db_data: